# -*- coding: utf-8 -*-
"""A2-5-threshold comparision.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i1sWI7sRukr2o4NjKxeYXtG2n_la0qy3
"""

import matplotlib.pyplot as plt
import numpy as np

threshold = [6,7,8,9,10,11]
number_of_feature = [81, 73, 63, 40, 22, 8]
baseline = [0.28125, 0.28645834, 0.32291666, 0.328125, 0.28125, 0.33854166]
casper = [0.234375, 0.23958333, 0.27083334, 0.25, 0.234375, 0.24479167]
deq_casper = [0.31770834, 0.25, 0.28645834, 0.265625, 0.22395833, 0.24479167]

plt.figure(figsize = (20,10))
plt.subplot(1,2,1)
plt.plot(threshold,baseline,label='Baseline',color='r')
plt.plot(threshold,casper, label='Casper', color='b')
plt.plot(threshold,deq_casper, label='Fixed Point Casper',color='g')
plt.ylabel('Average accuracy')
plt.xlabel('Threshold')
plt.grid()
plt.legend(loc='upper left')
plt.title("Model's performance with diferent theshold")
plt.subplot(1,2,2)
plt.plot(threshold,number_of_feature)
plt.grid()
plt.ylabel('Number of feature')
plt.xlabel('Threshold')
plt.title('Number of features vs threshold')
plt.show()

